all:
  children:
    dev:
      hosts:
        sandbox:
          ansible_connection: local
          ansible_host: 192.168.31.111
        docker-host:
          ansible_connection: docker
          ansible_host: docker-host
        win-host:
          ansible_host: 192.168.31.101
          ansible_user: vagrant
          ansible_password: "{{ws_passwd}}"
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5986
        lin-host:
          ansible_host: 192.168.0.18
          ansible_user: vagrant
          ansible_password: vagrant
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=120'