all:
  children:
    dev:
      hosts:
        sandbox:
          ansible_connection: local
          ansible_host: 192.168.31.111
        lin-host-18.04:
          ansible_host: 192.168.0.18
          ansible_user: vagrant
          ansible_password: vagrant
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=120'